app = "pasada-analytics-v2"
primary_region = "sin"

# Using Dockerfile instead of Heroku builder

[env]
  NODE_ENV = "production"
  PORT = "3001"
  SERVICE_TYPE = "analytics"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = [ "app" ]

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/health"

[[services.ports]]
  port = 80
  handlers = ["http"]
  force_https = true

[[services.ports]]
  port = 443
  handlers = ["tls", "http"]

[services.concurrency]
  type = "requests"
  hard_limit = 10
  soft_limit = 5

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = "512mb"
