app = "pasada-questdb-1757688431"
primary_region = "sin"

[experimental]
  init_limit_ulimit_nofile = 1048576

[mounts]
  source = "questdb_data"
  destination = "/var/lib/questdb"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = "1024mb"

[http_service]
  internal_port = 9000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[services]]
  internal_port = 9000
  protocol = "tcp"
  
  [[services.ports]]
    handlers = ["http"]
    port = 80
  
  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[[services]]
  internal_port = 9009
  protocol = "tcp"
  
  [[services.ports]]
    port = 9009
